/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Bairon Dajome
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        rBodega = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblBodega = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        rVenta = new javax.swing.JLabel();
        rCliente = new javax.swing.JLabel();
        rProveedor = new javax.swing.JLabel();
        escote = new javax.swing.JPanel();
        lblBarra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Configuracion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 50));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("Registro Venta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgVenta.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgVenta2.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgVenta2.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgVenta2.png"))); // NOI18N
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 130));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgDetall.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgDetalle2.png"))); // NOI18N
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgDetalle2.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgDetalle2.png"))); // NOI18N
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 130, 130));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setText("Resumen Ventas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgBodega.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgBodega2.png"))); // NOI18N
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgBodega2.png"))); // NOI18N
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgBodega2.png"))); // NOI18N
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 130, 130));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("Bodega");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/usuario.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 240, 150));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgPantalla.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 480, 340));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgSalir.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgSalir2.png"))); // NOI18N
        jButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgSalir2.png"))); // NOI18N
        jButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgSalir2.png"))); // NOI18N
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgMinimizar.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgMinimizar2.png"))); // NOI18N
        jButton5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgMinimizar2.png"))); // NOI18N
        jButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgMinimizar2.png"))); // NOI18N
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 33, 33));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Reportes");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 140, 50));

        rBodega.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rBodega.setForeground(new java.awt.Color(204, 204, 204));
        rBodega.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rBodega.setText("Bodega");
        jPanel1.add(rBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 40, 70, 30));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Usuario");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 70, 30));

        lblCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(204, 204, 204));
        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente.setText("Cliente");
        jPanel1.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 70, 30));

        lblBodega.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBodega.setForeground(new java.awt.Color(204, 204, 204));
        lblBodega.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBodega.setText("Bodega");
        jPanel1.add(lblBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 70, 30));

        lblProveedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(204, 204, 204));
        lblProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProveedor.setText("Proveedor");
        jPanel1.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 90, 30));

        rVenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rVenta.setForeground(new java.awt.Color(204, 204, 204));
        rVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rVenta.setText("Ventas");
        jPanel1.add(rVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 70, 30));

        rCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rCliente.setForeground(new java.awt.Color(204, 204, 204));
        rCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rCliente.setText("Cliente");
        jPanel1.add(rCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 60, 30));

        rProveedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rProveedor.setForeground(new java.awt.Color(204, 204, 204));
        rProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rProveedor.setText("Proveedor");
        jPanel1.add(rProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 40, 90, 30));

        escote.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgBarra.png"))); // NOI18N
        escote.add(lblBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(escote, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgPortada.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 383));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/imgPie.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1200, 170));

        jLabel17.setText("jLabel17");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel escote;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblBarra;
    public javax.swing.JLabel lblBodega;
    public javax.swing.JLabel lblCliente;
    public javax.swing.JLabel lblProveedor;
    public javax.swing.JLabel lblUsuario;
    public javax.swing.JLabel rBodega;
    public javax.swing.JLabel rCliente;
    public javax.swing.JLabel rProveedor;
    public javax.swing.JLabel rVenta;
    // End of variables declaration//GEN-END:variables
}
